import keyMirror from 'key-mirror';

export default keyMirror({
  ROUTER_STATE_CHANGE: null,

  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT: null,

  FETCH_PROFILE_SUCCESS: null,
  FETCH_PROFILE_FAILURE: null,

  SAVE_PROFILE: null,
  SAVE_PROFILE_SUCCESS: null,
  SAVE_PROFILE_FAILURE: null,

  FETCH_USERS_SUCCESS: null,
  FETCH_USERS_FAILURE: null,

  POST_MESSAGE: null,
  POST_MESSAGES_SUCCESS: null,
  POST_MESSAGES_FAILURE: null,

  LOAD_SINGLE_POST_SUCCESS: null,
  LOAD_SINGLE_POST_FAILURE: null,

  LOAD_POSTS: null,
  LOAD_PUBLISHED_POSTS_SUCCESS: null,
  LOAD_PUBLISHED_POSTS_FAILURE: null,
  LOAD_UNPUBLISHED_POSTS_SUCCESS: null,
  LOAD_UNPUBLISHED_POSTS_FAILURE: null,

  SAVE_POST: null,
  SAVE_POST_SUCCESS: null,
  SAVE_POST_FAILURE: null
});
