import keyMirror from 'key-mirror';

export default keyMirror({
  ROUTER_STATE_CHANGE: null,

  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT: null,

  FETCH_PROFILE_SUCCESS: null,
  FETCH_PROFILE_FAILURE: null,

  SAVE_PROFILE: null,
  SAVE_PROFILE_SUCCESS: null,
  SAVE_PROFILE_FAILURE: null,

  FETCH_USERS_SUCCESS: null,
  FETCH_USERS_FAILURE: null,

  FETCH_SINGLE_USER_SUCCESS: null,
  FETCH_SINGLE_USER_FAILURE: null,

  REQUEST_LESSON: null,
  REQUEST_LESSON_SUCCESS: null,
  REQUEST_LESSON_FAILURE: null,

  ADD_LESSON: null,
  ADD_LESSON_SUCCESS: null,
  ADD_LESSON_FAILURE: null,

  UPDATE_LESSON: null,
  UPDATE_LESSON_SUCCESS: null,
  UPDATE_LESSON_FAILURE: null,

  FETCH_LESSONS: null,
  FETCH_LESSONS_SUCCESS: null,
  FETCH_LESSONS_FAILURE: null,

  DELETE_LESSON: null,
  DELETE_LESSON_SUCCESS: null,
  DELETE_LESSON_FAILURE: null,

  FETCH_THREADS: null,
  FETCH_THREADS_SUCCESS: null,
  FETCH_THREADS_FAILURE: null,

  FETCH_MESSAGES: null,
  FETCH_MESSAGES_SUCCESS: null,
  FETCH_MESSAGES_FAILURE: null,

  POST_MESSAGE: null,
  POST_MESSAGES_SUCCESS: null,
  POST_MESSAGES_FAILURE: null,

  LOAD_POSTS: null,
  LOAD_PUBLISHED_POSTS_SUCCESS: null,
  LOAD_PUBLISHED_POSTS_FAILURE: null,
  LOAD_UNPUBLISHED_POSTS_SUCCESS: null,
  LOAD_UNPUBLISHED_POSTS_FAILURE: null,

  SAVE_POST: null,
  SAVE_POST_SUCCESS: null,
  SAVE_POST_FAILURE: null
});
